import type { Metadata } from 'next';
import ApiCostCalculator from '@/components/calculators/ApiCostCalculator';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import RelatedTools from '@/components/seo/RelatedTools';
import FAQSection from '@/components/seo/FAQSection';

export const metadata: Metadata = {
  title: 'Token Cost Calculator - Free AI Token Pricing Estimator',
  description:
    'Use this free Token Cost Calculator to estimate AI token pricing for Claude, GPT, Gemini, DeepSeek, Mistral, and Grok. Calculate input tokens, output tokens, API costs, daily cost, and monthly budget.',
  keywords: [
    'token cost calculator',
    'ai token cost calculator',
    'token pricing calculator',
    'llm token cost calculator',
    'api token cost calculator',
    'claude token cost',
    'gpt token cost',
    'openai token calculator',
  ],
  alternates: {
    canonical: 'https://aiapicost.tools/token-cost-calculator',
    languages: {
      en: 'https://aiapicost.tools/token-cost-calculator',
      zh: 'https://aiapicost.tools/zh/token-cost-calculator',
    },
  },
};

const faqItems = [
  {
    question: 'What is a token cost calculator?',
    answer:
      'A token cost calculator estimates how much an AI API request costs based on input tokens, output tokens, model pricing, request volume, and daily usage.',
  },
  {
    question: 'How do input and output tokens affect cost?',
    answer:
      'Most AI providers charge different prices for input and output tokens. Output tokens are often more expensive, so both values are needed for an accurate estimate.',
  },
  {
    question: 'Can I calculate monthly token costs?',
    answer:
      'Yes. Enter your average tokens per request and calls per day to estimate per-call, daily, and monthly token costs.',
  },
  {
    question: 'Does this token cost calculator support custom model pricing?',
    answer:
      'Yes. You can choose a listed model or enter custom input and output token prices for your own model or provider.',
  },
];

export default function TokenCostCalculatorPage() {
  return (
    <>
      <Header />
      <main className="flex-1 bg-[#0B0F19] relative overflow-hidden">
        <div className="absolute top-0 left-1/4 w-[600px] h-[600px] bg-orb bg-orb-purple animate-pulse-slow pointer-events-none" />
        <div className="absolute top-1/3 right-1/4 w-[400px] h-[400px] bg-orb bg-orb-cyan animate-pulse-slow pointer-events-none" style={{ animationDelay: '3s' }} />

        <section className="relative border-b border-white/[0.04] py-16 px-4">
          <div className="max-w-5xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 gradient-text">
              Token Cost Calculator
            </h1>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto mb-6">
              Calculate AI token costs for Claude, GPT, Gemini, DeepSeek, Mistral, Grok, and custom models.
            </p>
            <p className="text-sm text-gray-500 max-w-2xl mx-auto">
              Estimate input token cost, output token cost, API cost per call, daily token spend, and monthly AI budget in one free calculator.
            </p>
          </div>
        </section>

        <section className="relative py-10 px-4">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-xl font-bold text-white mb-6">AI Token Cost Calculator</h2>
            <ApiCostCalculator />
          </div>
        </section>

        <section className="relative border-t border-white/[0.04] py-16 px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl font-bold text-white mb-3 text-center">How token cost is calculated</h2>
            <p className="text-sm text-gray-500 text-center mb-10">
              Token pricing is based on model-specific input and output rates per million tokens.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {[
                { title: 'Input tokens', desc: 'Tokens sent to the model in your prompt, system message, tools, and context.' },
                { title: 'Output tokens', desc: 'Tokens generated by the model in the response. These usually cost more than input tokens.' },
                { title: 'Usage volume', desc: 'Requests per call and calls per day convert per-request token cost into daily and monthly cost.' },
              ].map((item) => (
                <div key={item.title} className="glass-card p-6 text-center">
                  <h3 className="font-semibold text-white text-sm mb-2">{item.title}</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <FAQSection title="Token Cost Calculator FAQ" items={faqItems} />
        <RelatedTools currentSlug="token-cost-calculator" />
      </main>
      <Footer />
    </>
  );
}
